# Generated by Django 5.2.8 on 2025-11-16 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_e', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('turno', models.CharField(blank=True, max_length=20, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_c', models.IntegerField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('rfc', models.CharField(blank=True, max_length=16, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('folio_c', models.IntegerField(primary_key=True, serialize=False)),
                ('no_lote', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('existencia', models.IntegerField(blank=True, null=True)),
                ('precio_c', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_v', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'producto_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_p', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('contacto', models.CharField(blank=True, max_length=70, null=True)),
                ('tel_contacto', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'supervisor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('folio_v', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PFisica',
            fields=[
                ('id_c', models.OneToOneField(db_column='id_c', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='fruteria_app.cliente')),
                ('nombre', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'p_fisica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PMoral',
            fields=[
                ('id_c', models.OneToOneField(db_column='id_c', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='fruteria_app.cliente')),
                ('razon_social', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'p_moral',
                'managed': False,
            },
        ),
    ]
