# Generated by Django 5.2.8 on 2025-11-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_p', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('ciudad', models.CharField(max_length=30)),
                ('contacto', models.CharField(max_length=70)),
                ('tel_contacto', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
    ]
